---
- name: "Ansible core version check ({{ ansible_version.full }} >= 2.21)"
  ansible.builtin.assert:
    that:
      - ansible_version is defined
      - ansible_version.full is version_compare('2.21', '>=')
    fail_msg: "Required version is 2.21, this is {{ ansible_version.full }}"
    quiet: true
  tags: always

- name: "Collection kubernetes.core version check ({{ lookup('community.general.collection_version', 'kubernetes.core') }} >= 6.4)"
  ansible.builtin.assert:
    that:
      - lookup('community.general.collection_version', 'kubernetes.core') is version('6.4','>=')
    fail_msg: "Required version is 6.4, this is {{lookup('community.general.collection_version', 'kubernetes.core') }}"
    quiet: true
  tags: always

- name: "check k8s_context and k8s_namespace"
  ansible.builtin.assert:
    that:
      - k8s_context is defined
      - k8s_namespace is defined
  tags: always

- name: "Cloud Native PostGres setup"
  ansible.builtin.include_tasks:
    file: postgres.yml
    apply:
      tags:
        - postgres
  tags: postgres

- name: "create Secret with deploy tokens for reading GitLab registry"
  kubernetes.core.k8s:
    state: present
    resource_definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "gitlab-cesnet-secret"
        namespace: "{{ k8s_namespace }}"
        annotations:
          field.cattle.io/description: "holds authentication token for GitLab docker registry"
      type: kubernetes.io/dockerconfigjson
      stringData:
        .dockerconfigjson: "{{ docker_config_structure | to_json }}"
  vars:
    docker_config_structure:
      auths:
        gitlab-registry.cesnet.cz:
          username: gitlab-deploy-token-712
          password: gldt-TcDbEs8Yj-cX4KPmM1Wq
          auth: "{{ 'gitlab-deploy-token-712:gldt-TcDbEs8Yj-cX4KPmM1Wq' | b64encode }}"
  tags:
    - perun_gitlab

- name: "certificates setup"
  ansible.builtin.include_tasks:
    file: perun_certs.yml
    apply:
      tags:
        - perun_certs
  tags:
    - perun_certs

- name: "Perun RPC setup"
  ansible.builtin.include_tasks:
    file: perun_rpc.yml
    apply:
      tags:
        - perun_rpc
        - perun_config
  tags:
    - perun_rpc
    - perun_config

- name: "print shell commands info"
  tags:
    - perun_rpc
    - perun_config
    - perun_shells
  block:
    - name: "get pod info"
      kubernetes.core.k8s_info:
          kind: Pod
          namespace: "{{ k8s_namespace }}"
          context: "{{ k8s_context }}"
          label_selectors:
          - app=perun-rpc
      register: perunrpc_pod_info
#    - name: "shell in perun-rpc"
#      debug:
#        msg: "kubectl exec -it {{ perunrpc_pod_info.resources[0].metadata.name }} --container {{ perunrpc_pod_info.resources[0].spec.containers[0].name }} -- /bin/bash"
    - name: "shell in perun-rpc"
      debug:
        msg: "kubectl exec -it deployment/perun-rpc-deployment --container perun-rpc-container -- /bin/bash"
    - name: "copy rpc webapp"
      when: perun_rpc_k8s_debug
      debug:
        msg: "kubectl cp perun-rpc.war {{ perunrpc_pod_info.resources[0].metadata.name }}:/opt/tomcat/webapps/"

#DONE
# - OS setup - NTP, monitoring, unattended upgrades, Yubikeys - not needed
# - users and home dirs - not needed
# - volumes - /etc/perun and /home/perun - do it in respective pods


#TODO
# - perun_rpc
# - configs - computes CORS domains
# - certificates
# - firewall
# - logging and remote logging
# - sendmail
# - LDAP
# - group specific tasks
# - site specific tasks
# - perun-2-perun sync
# - perun_auditlogger
# - perun_ldapc
# - perun_engine
# - perun_apache
# - perun_cli

