- name: "set helm chart metadata"
  set_fact:
    chart_name: perunrpc
    chart_version: 1.0.0
    chart_description: Perun RPC chart
    chart_app_version: "{{ perun_rpc_container_version }}"

- name: "compute temporary chart directory name"
  set_fact:
    chart_path: "localcharts/{{ chart_name }}-{{ inventory_hostname }}"

- name: "create directories for temporary chart"
  loop:
    - "{{ chart_path }}"
    - "{{ chart_path }}/templates"
  file:
    state: directory
    path: "{{ item }}"

- name: "generate Chart.yaml file"
  ansible.builtin.template:
    src: "templates/Chart.yaml.j2"
    dest: "{{ chart_path }}/Chart.yaml"

- name: "generate values.yaml file"
  ansible.builtin.template:
    src: "templates/values.yaml.j2"
    dest: "{{ chart_path }}/values.yaml"

# prepare all files for /etc/perun as Secret items, encode paths by replacing "/" with "__", decode them back in Deployment
- name: "block for /etc/perun files"
  block:
    - name: "generate config files from templates"
      loop:
        - server.xml
        - jdbc.properties
        - perun-apps-config.yml
        - perun-roles.yml
        - perun-web-gui.properties
        - perun.properties
        - perun-registrar-lib.properties
        - perun-dispatcher.properties
        - perun-namespaces.properties
      set_fact:
        perunrpc_etc_secret_data: "{{ perunrpc_etc_secret_data | default({}) | combine({item: (lookup('ansible.builtin.template', 'perun/'+item+'.j2') | b64encode)}) }}"
      vars:
        perun_postgresql_jdbc_url: "jdbc:postgresql://perundb-rw:5432/perun"
        perun_postgresql_db_user_password: "{{ perun_cnpg_cluster_user_password }}"

    - name: "add config files"
      loop:
        - perun-extSources.xml
        - login-namespaces-rules-config.yml
        - logback.xml
      set_fact:
        perunrpc_etc_secret_data: "{{ perunrpc_etc_secret_data| combine( { item: (lookup('ansible.builtin.file', lookup('ansible.builtin.first_found', files=[item], paths=['files/'+ perun_instance_hostname, 'files/', 'files/perun/' ])) | b64encode)}) }}"

    - name: "find optional files"
      loop:
        - tomcat_init.sh
        - perun-oidc-config.yml
      ansible.builtin.stat:
        path: "files/{{ perun_instance_hostname }}/{{ item }}"
      register: optional_files

    - name: "add optional files"
      loop: "{{ optional_files.results }}"
      loop_control:
        label: "{{ item.item }} - {{ item.stat.exists }}"
      when: item.stat.exists
      set_fact:
        perunrpc_etc_secret_data: "{{ perunrpc_etc_secret_data| combine( { (item.stat.path|basename): ( lookup('ansible.builtin.file',item.stat.path) | b64encode)}) }}"

    - name: "find modules"
      find:
        paths: "files/{{ perun_instance_hostname }}/modules/"
        recurse: yes
        file_type: file
      register: etc_modules

    - name: "add modules"
      loop: "{{ etc_modules.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
      set_fact:
        perunrpc_etc_secret_data: "{{ perunrpc_etc_secret_data| combine({ (item.path | relpath('files/'+perun_instance_hostname) | replace('/', '__')): (lookup('ansible.builtin.file',item.path) | b64encode) }) }}"

    - name: "find files in perun_rpc_etc"
      find:
        paths: "files/{{ perun_instance_hostname }}/perun_rpc_etc/"
        recurse: yes
        file_type: file
      register: perun_rpc_etc

    - name: "add files in perun_rpc_etc"
      set_fact:
        perunrpc_etc_secret_data: "{{ perunrpc_etc_secret_data | combine({ (item.path | relpath('files/'+perun_instance_hostname+'/perun_rpc_etc/') | replace('/', '__')): (lookup('ansible.builtin.file',item.path) | b64encode) }) }}"
      loop: "{{ perun_rpc_etc.files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: "prepare mount items"
      set_fact:
        perunrpc_etc_secret_volume_items: "{{ perunrpc_etc_secret_volume_items | default([]) + [{ 'key': item, 'path': (item| replace('__', '/')) }] }}"
      loop: "{{ perunrpc_etc_secret_data.keys()}}"

- name: "/home/perun files"
  block:
    - name: "init lists"
      set_fact:
        perunrpc_home_secret_data:
          README.txt: "{{ 'this folder is created from Kubernetes Secret' | b64encode }}"
          ".vimrc": "{{ perun_vimrc| b64encode }}"

    - name: "find files in perun_rpc_home"
      find:
        paths: "files/{{ perun_instance_hostname }}/perun_rpc_home/"
        recurse: yes
        file_type: file
      register: perun_rpc_home

    - name: "add files in perun_rpc_home"
      set_fact:
        perunrpc_home_secret_data: "{{ perunrpc_home_secret_data | combine({ (item.path | relpath('files/'+perun_instance_hostname+'/perun_rpc_home/') | replace('/', '__')): (lookup('ansible.builtin.file',item.path) | b64encode) }) }}"
      loop: "{{ perun_rpc_home.files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: "prepare mount items"
      set_fact:
        perunrpc_home_secret_volume_items: "{{ perunrpc_home_secret_volume_items | default([]) + [{ 'key': item, 'path': (item| replace('__', '/')) }] }}"
      loop: "{{ perunrpc_home_secret_data.keys()}}"

#TODO
# logovani
# perun_sync - externí perun nemá kam zapisovat, když to není VM

# generate YAML objects
- name: "generate YAML files in {{ chart_path}} }}/templates/ directory"
  loop:
    - perun-rpc-secret-etc-perun.yaml
    - perun-rpc-secret-home-perun.yaml
    - perun-rpc-persistent-volume-claim-logs.yaml
    - perun-rpc-deployment.yaml
  ansible.builtin.template:
    src: "templates/charts/{{ chart_name }}/{{ item }}.j2"
    dest: "{{ chart_path }}/templates/{{ item }}"

- name: "apply chart"
  kubernetes.core.helm:
    chart_ref: "{{ chart_path }}"
    release_namespace: "{{ k8s_namespace }}"
    context: "{{ k8s_context }}"
    release_name: perun-rpc
    release_state: present

- name: "debug info"
  when: perun_rpc_k8s_debug
  block:
    - name: "get pod info"
      kubernetes.core.k8s_info:
          kind: Pod
          namespace: "{{ k8s_namespace }}"
          context: "{{ k8s_context }}"
          label_selectors:
          - app=perun-rpc
      register: perunrpc_pod_info
    - name: "command for shell"
      debug:
        msg: "kubectl exec -it {{ perunrpc_pod_info.resources[0].metadata.name }} --container {{ perunrpc_pod_info.resources[0].spec.containers[0].name }} -- /bin/bash"